import {
  Property,
  StoreScope,
  TriggerStrategy,
  createTrigger,
} from '@activepieces/pieces-framework';
import {
  MarkdownVariant,
  ChatFormResponse,
  ChatFlowHistoryMessage,
  CHAT_HISTORY_STORE_PREFIX,
  CHAT_HISTORY_MAX_SESSION_ID_LENGTH,
} from '@activepieces/shared';

const responseMarkdown = `
This trigger sets up a chat interface. Ensure that **Respond on UI** is used in your flow`;

const markdown = `
**Published Chat URL:**
\`\`\`text
{{chatUrl}}
\`\`\`
Use this for production, views the published version of the chat flow.

**Embed on your website:**
\`\`\`html
{{chatEmbedCode}}
\`\`\`
Paste the snippet before the closing \`</body>\` tag of your site to get a floating chat bubble.

**Conversation memory:** previous messages of the session are available in the trigger output as \`history\` — map it into your AI step's prompt to give the bot memory.
<br>
<br>
`;

export const onChatSubmission = createTrigger({
  name: 'chat_submission',
  displayName: 'Chat UI',
  description: 'Trigger the flow by sending a message',
  aiMetadata: {
    description: 'Fires each time a person sends a message in the hosted chat interface generated by this trigger, carrying the message text, the chat session id that groups one conversation, and any attached files. Represents a single turn of a human conversation with the flow, so the session id is what ties multiple turns together. The sender waits for a reply, so the flow must call the Respond on UI action; submissions missing a chat id or message are rejected.',
  },
  props: {
    about: Property.MarkDown({
      value: markdown,
      variant: MarkdownVariant.BORDERLESS,
    }),
    responseMarkdown: Property.MarkDown({
      value: responseMarkdown,
      variant: MarkdownVariant.WARNING,
    }),
    botName: Property.ShortText({
      displayName: 'Bot Name',
      description: 'The name of the chatbot',
      required: true,
      defaultValue: 'AI Bot',
    }),
  },
  sampleData: {
    sessionId: 'kZqmnKNzhNvXnkPgaTBk3',
    message: 'What is the status of my order?',
    files: [],
    history: [
      {
        role: 'user',
        content: 'Hi there',
        timestamp: '2026-01-01T10:00:00.000Z',
      },
      {
        role: 'bot',
        content: 'Hello! How can I help you today?',
        timestamp: '2026-01-01T10:00:02.000Z',
      },
    ],
  },
  type: TriggerStrategy.WEBHOOK,
  async onEnable() {
    return;
  },
  async onDisable() {
    return;
  },
  async run(ctx) {
    const item = ctx.payload.body as { chatId?: string; message?: string };
    if (!item.chatId) {
      throw new Error('Chat ID is required');
    }
    if (!item.message) {
      throw new Error('Message is required');
    }
    const files = Object.entries(item)
      .filter(([key]) => key.startsWith('file'))
      .map(([key, value]) => {
        const index = Number(key.split('[')[1].split(']')[0]);
        return [index, value] as const;
      })
      .sort(([indexA], [indexB]) => indexA - indexB)
      .map(([_, value]) => value);

    // Conversation memory: the server appends each exchange to the store
    // after the flow responds; overly long session ids are skipped to stay
    // within the 128-char store key limit.
    let history: ChatFlowHistoryMessage[] = [];
    if (item.chatId.length <= CHAT_HISTORY_MAX_SESSION_ID_LENGTH) {
      history =
        (await ctx.store.get<ChatFlowHistoryMessage[]>(
          `${CHAT_HISTORY_STORE_PREFIX}${item.chatId}`,
          StoreScope.FLOW
        )) ?? [];
    }

    const response: ChatFormResponse = {
      sessionId: item.chatId,
      message: item.message,
      files,
      history,
    }
    return [response];
  },
});
